### ISSUE TITLE
Web console fails to yield result of compilation

### ISSUE THREAD

**Issue by codeslinger** [Whiley/WhileyLabs#2]
When attempting to compile and verify the below code, the UI creates the spinner but never returns the results. The Javascript console for the page yields the following:

```
jquery.js:4 POST http://localhost:8080/compile net::ERR_CONNECTION_RESET
send @ jquery.js:4
ajax @ jquery.js:4
n.(anonymous function) @ jquery.js:4
compile @ whileyweb.js:106
onclick @ (index):18
```

This occurs on both Chrome and Chromium 60, macOS and Linux, on both the whileylabs.com instance and a local instance running from commit hash db40454 (on the `develop` branch). I couldn't even paste the code into the edit field in Firefox to try it out there.

Code used:

```
function find(int[] xs, int target) -> (int rv)
requires |xs| > 0
ensures all { i in 0..|xs| | rv <= i }
ensures some { i in 0..|xs| | rv == i }:
    int lower = 0
    int upper = |xs|
    int cursor = (lower + upper) / 2
    while lower <= upper
    where cursor >= lower && cursor <= upper:
        int value = xs[cursor]
        if target < value:
            upper = cursor
        else if target > value:
            lower = cursor + 1
        else:
            return cursor
        cursor = (lower + upper) / 2
    return lower
```

**Comment by codeslinger** [comment]
What I assume is the previous version of this UI, found at http://whiley.org/play/, does return the results of compilation/verification.

**Comment by codeslinger** [comment]
Does a similar thing in Firefox Nightly 57, but doesn't even emit an error in the JS console.

**Comment by codeslinger** [comment]
I tried to compile this code with the command-line tools and received this result:

```
> wy jvmcompile --verify x.whiley 

WARNING: version numbering unavailable
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: need to support division
        at wyc.commands.Compile.compile(Compile.java:352)
        at wyjc.commands.JvmCompile.compile(JvmCompile.java:121)
        at wyc.commands.Compile.execute(Compile.java:296)
        at wyc.commands.Compile.execute(Compile.java:1)
        at wycc.WyMain.main(WyMain.java:92)
Caused by: java.lang.IllegalArgumentException: need to support division
        at wytp.proof.util.Arithmetic.asPolynomial(Arithmetic.java:58)
        at wytp.proof.rules.Simplification.normaliseBounds(Simplification.java:740)
        at wytp.proof.rules.Simplification.simplifyArithmeticEquality(Simplification.java:261)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:84)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:160)
        at wytp.proof.rules.Simplification.simplifyConjunct(Simplification.java:106)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:74)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:160)
        at wytp.proof.rules.Simplification.simplifyConjunct(Simplification.java:106)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:74)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:160)
        at wytp.proof.rules.Simplification.simplifyConjunct(Simplification.java:106)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:74)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:160)
        at wytp.proof.rules.Simplification.simplifyDisjunct(Simplification.java:132)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:76)
        at wytp.proof.rules.Simplification.simplifyQuantifier(Simplification.java:181)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:79)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:160)
        at wytp.proof.rules.Simplification.simplifyDisjunct(Simplification.java:132)
        at wytp.proof.rules.Simplification.simplify(Simplification.java:76)
        at wytp.proof.rules.Simplification.apply(Simplification.java:50)
        at wytp.proof.util.AbstractProofRule.apply(AbstractProofRule.java:53)
        at wytp.provers.AutomatedTheoremProver.checkUnsat(AutomatedTheoremProver.java:222)
        at wytp.provers.AutomatedTheoremProver.checkValidity(AutomatedTheoremProver.java:172)
        at wytp.provers.AutomatedTheoremProver.check(AutomatedTheoremProver.java:146)
        at wytp.provers.AutomatedTheoremProver.check(AutomatedTheoremProver.java:129)
        at wyal.tasks.CompileTask.build(CompileTask.java:157)
        at wybs.util.StdBuildRule.apply(StdBuildRule.java:107)
        at wybs.util.StdProject.build(StdProject.java:256)
        at wyc.commands.Compile.compile(Compile.java:332)
        ... 4 more
```

Perhaps this exception is being thrown in the UI server and its not responding properly to the client in that case?

**Comment by DavePearce** [comment]
Hey Toby,

Yeah, Ok, looks like its throwing an exception on the back end.  That's expected, since I know division still needs to be implemented.  But, it should be reporting the error to the client though, so that needs to be fixed --- thanks.

FYI, for testing, you can run the site locally by just cloning the repo:

https://github.com/Whiley/WhileyWeb

**Comment by codeslinger** [comment]
Yeah, I did that and got the same results as on whileylabs.com

**Comment by DavePearce** [comment]
Ok, have implemented a fix for this now which simply reports the internal failure in the client rather than just ignoring it.  In fact, it will report any exceptions caught during compilation which is probably a good thing.

Next, will update whileylabs.com

**Comment by DavePearce** [comment]
Ok, whileylabs.com is updated.
